### ISSUE TITLE
在分布式系统，能否保证全局唯一

### ISSUE THREAD

**Issue by 9-4-6** [fxlae/typeid-java#2]
在分布式系统，能否保证全局唯一

**Comment by fxlae** [comment]
As far as I understand your question, it depends on your requirements. TypeIDs are based on UUID version 7. UUIDv7 is designed to minimize the risk of collisions to a very low probability by incorporating the current timestamp as well as a random number. Although there's a theoretical possibility of non-uniqueness, the practical likelihood of such an event in UUIDv7 is extremely low, depending on the amount of ids generated within the same millisecond. UUIDs in general are designed to be used in distributed systems.
