### ISSUE TITLE
How we should store data in database ?

### ISSUE THREAD

**Issue by tabbi-yellow** [fxlae/typeid-java#3]
To be consistent across application we should store the string version "user_01h455vb4pex5vsknk084sn02q" or just uuid and on code level add prefix ?

**Comment by fxlae** [comment]
I don't think there's a general opinion on this, but here are my thoughts.

In general, it's of course possible to store the entire string, which is the easiest and most straightforward way. Quote from the README:

> K-Sortable: TypeIDs are K-sortable and can be used as the primary key in a database while ensuring good locality.

However, this applies when storing one TypeID type per index column. Mixing TypeIDs with different prefixes in the same column can negatively impact locality and make inserts more costly. Generally, this shouldn't be an issue as storing different ID types in the same column is uncommon.

If you have large tables, another aspect to consider is efficiency. Storing a TypeID with its prefix (let's say "user") as (var)char requires 31 bytes (4 for the prefix, 1 for the underscore, 26 bytes for the UUID), whereas solely storing the UUID as a binary type requires 16 bytes, halving the index size.

A third option is a hybrid approach, storing both prefix and UUID in separate columns, with only the UUID indexed and stored in binary form.

So the answer is "it depends" ;). For smaller applications, storing the whole TypeID is totally fine, but as soon as index performance and efficiency matter, storing the UUID suffix in its native form would be the first thing to consider.

**Comment by tabbi-yellow** [comment]
Probably starting with uuidv7 in binary form would be the best option. The only problem I see you have to always decode typeid from logs to match it with the row in database.

Thank you for the update !
